name: Validate

on: 
  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '*.sh'
      - '.github/workflows/*.yaml'

jobs:
  build-project:
    name: Build Web-UI App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build App
        run: npm run build
